### PR TITLE
Remove language option

### PR DESCRIPTION
**Pull request by rhyspowell**
Api appears to have removed all but EN as a language choice

### CODE REVIEW

**Review by bbelderbos — APPROVED** [review]
Looks good, thanks Rhys

**Comment by bbelderbos** [comment]
@rhyspowell [other 2 tests are still failing as well](https://github.com/PyBites-Open-Source/pybites-tools/runs/5886138322?check_suite_focus=true). The payload also changed (`origin` keyword, see #28). 

I think you want to do some mocking instead, pytest-vcr is quite nice.

**Comment by rhyspowell** [comment]
Will take a look again, it passed on mine and the logs are missing from the tests when I look on the app

**Comment by rhyspowell** [comment]
Also, as this doesn't have any real business logic, dropping down to a unit test level and using mocks is the wrong thing to do. If we did that we would think the module is fine but we need to be at the integration test level as we are dependant upon a 3rd party.

**Comment by bbelderbos** [comment]
Yeah good point and distinction. If only mocking we're not testing it end-to-end. Let's just leave it as "real deal" then and fix them. The good thing is that the tests notified us of their API change. Thanks.

**Pull request merged**
